dia = input("Informe seu dia de nascimento: ")
mes = input("Informe seu mês de nascimento: ")
ano = input("Informe seu ano de nascimento: ")
print(" CONFIRA A DATA ")
print(" Você nasceu no dia ",dia," de",mes," de",ano,". Correto?")
